-- Upgrade the original pull-apart branch database to the merged main schema.
-- Generated by: node scripts/build-legacy-upgrade.mjs
-- Run this ENTIRE file in Supabase SQL Editor. No account/media/memory reset.
-- Includes the equivalent of main 002–004 and 006–011. Deliberately skips
-- 005_consolidate_hackmit_demo: a demo-data rewrite is not a schema upgrade.
-- Safe to retry: one transaction; existing rows/IDs are retained.
-- Legacy memories/faces are NOT automatically relabeled as verified evidence.
begin;

do $$ begin
  if to_regclass('public.family_members') is null then
    raise exception 'This upgrade requires the original family account schema. For a new database, use the numbered migrations.';
  end if;
  if exists(select 1 from public.weaver_questions where status='open' and gap_node_id is not null
    group by family_id,gap_node_id,gap_type having count(*)>1)
    or exists(select 1 from public.memories where kind='answer' and source_question_id is not null
      group by source_question_id having count(*)>1) then
    raise exception 'Duplicate question/answer records need review before upgrading. Nothing was changed.';
  end if;
end $$;

-- From 002_atomic_ingestion.sql
-- Legacy rows deliberately remain unverified. Only server ingestion sets source/model.
alter table public.memories add column if not exists source jsonb;
alter table public.memories add column if not exists verified_facts jsonb not null default '[]'::jsonb;
alter table public.face_embeddings add column if not exists model text;

create table if not exists public.ingestion_receipts (
  id uuid primary key,
  family_id text not null,
  contributor_id uuid not null references public.relatives(id) on delete cascade,
  request_hash text not null,
  response jsonb not null,
  source jsonb not null,
  created_at timestamptz not null default now()
);
alter table public.ingestion_receipts enable row level security;
revoke all on public.ingestion_receipts from anon, authenticated;
grant all on public.ingestion_receipts to service_role;

create or replace function public.commit_ingestion(payload jsonb)
returns jsonb
language plpgsql
set search_path = public, extensions
as $$
declare
  operation_id uuid := (payload->>'id')::uuid;
  family text := payload->>'family_id';
  contributor uuid := (payload->>'contributor_id')::uuid;
  receipt public.ingestion_receipts%rowtype;
  memory_record public.memories%rowtype;
  face_record public.face_embeddings%rowtype;
  question public.weaver_questions%rowtype;
  node_record public.graph_nodes%rowtype;
  edge_record public.graph_edges%rowtype;
  provenance_record public.provenance%rowtype;
  item jsonb;
begin
  if family is null or contributor is null or operation_id is null
     or payload->>'request_hash' is null or payload->'response' is null
     or payload->'source'->>'type' is distinct from 'human' then
    raise exception 'Invalid ingestion payload';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(family, 0));
  if not exists (select 1 from public.relatives where id = contributor and family_id = family) then
    raise exception 'Contributor scope mismatch';
  end if;
  select * into receipt from public.ingestion_receipts where id = operation_id;
  if found then
    if receipt.family_id is distinct from family
       or receipt.contributor_id is distinct from contributor
       or receipt.request_hash is distinct from payload->>'request_hash' then
      raise exception 'Idempotency conflict' using errcode = '23505';
    end if;
    return receipt.response;
  end if;

  if payload ? 'face' then
    face_record := jsonb_populate_record(null::public.face_embeddings,
      (payload->'face') || jsonb_build_object('descriptor', (payload->'face'->'descriptor')::text,
        'model', payload->'source'->>'model'));
    if face_record.id is distinct from operation_id
       or face_record.family_id is distinct from family
       or face_record.contributor_id is distinct from contributor
       or payload->'source'->>'consent' is distinct from 'true'
       or payload->'source'->>'model' is distinct from 'face-api-1.7.15:ssd-mobilenetv1:landmark68:recognition128:rgb-exif-v1'
       or vector_dims(face_record.descriptor) is distinct from 128 then
      raise exception 'Invalid enrollment';
    end if;
    if not exists (select 1 from public.memories where id = face_record.memory_id
      and family_id = family and contributor_id = contributor and kind = 'photo')
      or not exists (select 1 from public.graph_nodes where id = face_record.person_node_id
      and family_id = family and type = 'person') then
      raise exception 'Enrollment scope mismatch';
    end if;
    insert into public.face_embeddings select face_record.*;
    insert into public.provenance(memory_id, node_id, contributor_id)
      select face_record.memory_id, face_record.person_node_id, contributor
      where not exists (select 1 from public.provenance where memory_id = face_record.memory_id
        and node_id = face_record.person_node_id and contributor_id = contributor);
  else
    memory_record := jsonb_populate_record(null::public.memories,
      (payload->'memory') || jsonb_build_object('embedding', (payload->'memory'->'embedding')::text));
    memory_record.source := payload->'source';
    memory_record.verified_facts := coalesce(payload->'memory'->'verified_facts', '[]'::jsonb);
    if memory_record.id is distinct from operation_id
       or memory_record.family_id is distinct from family
       or memory_record.contributor_id is distinct from contributor then
      raise exception 'Memory scope mismatch';
    end if;
    if memory_record.kind = 'answer' then
      select * into question from public.weaver_questions
        where id = memory_record.source_question_id for update;
      if not found or question.family_id is distinct from family
         or question.target_relative_id is distinct from contributor then
        raise exception 'Question scope mismatch';
      end if;
      if question.status <> 'open' then
        raise exception 'Question already answered' using errcode = '23505';
      end if;
    elsif memory_record.source_question_id is not null then
      raise exception 'Unexpected question';
    end if;
    memory_record.created_at := now();
    insert into public.memories select memory_record.*;

    for item in select value from jsonb_array_elements(payload->'nodes') loop
      node_record := jsonb_populate_record(null::public.graph_nodes, item);
      if node_record.family_id is distinct from family then raise exception 'Node scope mismatch'; end if;
      node_record.created_at := now();
      insert into public.graph_nodes select node_record.* on conflict (id) do nothing;
      if not exists (select 1 from public.graph_nodes where id = node_record.id
        and family_id = family and type = node_record.type and label = node_record.label) then
        raise exception 'Node collision';
      end if;
    end loop;
    for item in select value from jsonb_array_elements(payload->'edges') loop
      edge_record := jsonb_populate_record(null::public.graph_edges, item);
      if edge_record.family_id is distinct from family
         or not exists (select 1 from public.graph_nodes where id = edge_record.from_node and family_id = family)
         or not exists (select 1 from public.graph_nodes where id = edge_record.to_node and family_id = family)
         or edge_record.rel not in ('sibling_of','child_of','parent_of','grandchild_of','spouse_of','friend_of',
           'participates_in','started_by','taught_by','origin','located_at','wears','owns','made','happens_on') then
        raise exception 'Invalid edge';
      end if;
      edge_record.created_at := now();
      insert into public.graph_edges select edge_record.* on conflict (id) do nothing;
      if not exists (select 1 from public.graph_edges where id = edge_record.id and family_id = family
        and from_node = edge_record.from_node and to_node = edge_record.to_node and rel = edge_record.rel) then
        raise exception 'Edge collision';
      end if;
    end loop;
    for item in select value from jsonb_array_elements(payload->'provenance') loop
      provenance_record := jsonb_populate_record(null::public.provenance, item);
      if provenance_record.memory_id is distinct from operation_id
         or provenance_record.contributor_id is distinct from contributor
         or (provenance_record.node_id is null) = (provenance_record.edge_id is null)
         or (provenance_record.node_id is not null and not exists
           (select 1 from public.graph_nodes where id = provenance_record.node_id and family_id = family))
         or (provenance_record.edge_id is not null and not exists
           (select 1 from public.graph_edges where id = provenance_record.edge_id and family_id = family)) then
        raise exception 'Provenance scope mismatch';
      end if;
      insert into public.provenance select provenance_record.* on conflict (id) do nothing;
    end loop;
    -- Literal spans must belong to this human source and a subject linked by this memory.
    for item in select value from jsonb_array_elements(memory_record.verified_facts) loop
      if item->>'memoryId' is distinct from operation_id::text
         or item->>'contributorId' is distinct from contributor::text
         or nullif(item->>'text', '') is null
         or jsonb_typeof(item->'sourceSpan') is distinct from 'object'
         or jsonb_typeof(item->'sourceSpan'->'start') is distinct from 'number'
         or jsonb_typeof(item->'sourceSpan'->'end') is distinct from 'number'
         or (item->'sourceSpan'->>'start')::int < 0
         or (item->'sourceSpan'->>'end')::int <= (item->'sourceSpan'->>'start')::int
         or position(item->>'text' in coalesce(memory_record.transcript, memory_record.source->>'caption', '')) = 0
         or not exists (select 1 from public.provenance where memory_id = operation_id
           and node_id = (item->>'subjectNodeId')::uuid and contributor_id = contributor) then
        raise exception 'Invalid verified human fact';
      end if;
    end loop;
    if memory_record.kind = 'answer' then
      update public.weaver_questions set status = 'answered', answer_memory_id = operation_id
        where id = memory_record.source_question_id;
    end if;
  end if;

  insert into public.ingestion_receipts(id, family_id, contributor_id, request_hash, response, source)
    values (operation_id, family, contributor, payload->>'request_hash', payload->'response', payload->'source');
  return payload->'response';
end;
$$;

revoke all on function public.commit_ingestion(jsonb) from public, anon, authenticated;
grant execute on function public.commit_ingestion(jsonb) to service_role;

-- From 003_family_boundary_and_weaver.sql
alter table public.recall_events add column if not exists face_outcome jsonb;
alter table public.recall_events add column if not exists evidence jsonb;
alter table public.recall_events add column if not exists reason_code text;
alter table public.recall_events add column if not exists selected_fact_ids jsonb not null default '[]'::jsonb;

-- Claims are admin-issued app_metadata, never user-editable user_metadata.
-- Definer avoids recursive relatives RLS while requiring a real membership row.
create or replace function public.kin_has_membership() returns boolean language sql stable security definer
set search_path = public, pg_temp as $$
  select exists (select 1 from public.relatives r where r.id::text = auth.jwt()->'app_metadata'->>'kin_contributor_id'
    and r.family_id = auth.jwt()->'app_metadata'->>'kin_family_id')
$$;
revoke all on function public.kin_has_membership() from public, anon;
grant execute on function public.kin_has_membership() to authenticated, service_role;
do $$
declare t text;
begin
  foreach t in array array['relatives','wearer','memories','graph_nodes','graph_edges','recall_events','weaver_questions'] loop
    execute format('drop policy if exists %I on public.%I', 'anon read ' || t, t);
    execute format('drop policy if exists family_read on public.%I', t);
    execute format('create policy family_read on public.%I for select to authenticated using (family_id = (auth.jwt()->''app_metadata''->>''kin_family_id'') and exists (select 1 from public.relatives membership where membership.id::text = (auth.jwt()->''app_metadata''->>''kin_contributor_id'') and membership.family_id = (auth.jwt()->''app_metadata''->>''kin_family_id'')))', t);
  end loop;
end $$;
-- Avoid recursive policy evaluation on relatives.
drop policy if exists family_read on public.relatives;
drop policy if exists family_read on public.relatives;
create policy family_read on public.relatives for select to authenticated using (
  family_id = auth.jwt()->'app_metadata'->>'kin_family_id'
  and public.kin_has_membership()
);
drop policy if exists "anon read provenance" on public.provenance;
drop policy if exists family_read on public.provenance;
create policy family_read on public.provenance for select to authenticated using (
  exists (select 1 from public.memories m where m.id = memory_id
    and m.family_id = auth.jwt()->'app_metadata'->>'kin_family_id')
);
drop policy if exists "anon read face_embeddings" on public.face_embeddings;
-- Descriptors never leave privileged server access, including authenticated browsers.
revoke all on public.face_embeddings from anon, authenticated;
revoke all on function public.match_faces(vector, text, integer) from public, anon, authenticated;
revoke all on function public.match_memories(vector, uuid, integer) from public, anon, authenticated;
grant execute on function public.match_faces(vector, text, integer) to service_role;
grant execute on function public.match_memories(vector, uuid, integer) to service_role;

create or replace function public.match_subject_memories(query vector(1536), family text, contributor uuid, subject uuid, k int)
returns table (id uuid, summary text, similarity float)
language sql stable set search_path = public, extensions as $$
  select m.id, m.summary, 1 - (m.embedding <=> query) as similarity
  from public.memories m
  where m.family_id = family and m.contributor_id = contributor
    and m.source->>'type' = 'human'
    and jsonb_array_length(m.verified_facts) > 0
    and exists (select 1 from public.provenance p where p.memory_id = m.id
      and p.node_id = subject and p.contributor_id = contributor)
  order by m.embedding <=> query
  limit greatest(0, least(k, 50))
$$;
revoke all on function public.match_subject_memories(vector,text,uuid,uuid,integer) from public, anon, authenticated;
grant execute on function public.match_subject_memories(vector,text,uuid,uuid,integer) to service_role;

-- At most one unfinished question for a graph gap, including concurrent run requests.
create unique index if not exists weaver_one_open_gap on public.weaver_questions(family_id, gap_node_id, gap_type) where status = 'open';
create unique index if not exists weaver_one_answer on public.memories(source_question_id) where kind = 'answer';

update storage.buckets set public = false where id = 'media';
drop policy if exists family_media_read on storage.objects;
create policy family_media_read on storage.objects for select to authenticated using (
  bucket_id = 'media' and (storage.foldername(name))[1] = auth.jwt()->'app_metadata'->>'kin_family_id'
  and exists (select 1 from public.relatives r where r.id::text = auth.jwt()->'app_metadata'->>'kin_contributor_id'
    and r.family_id = auth.jwt()->'app_metadata'->>'kin_family_id')
);
-- Full row payloads make update/delete subscriptions deterministic under family RLS.
alter table public.weaver_questions replica identity full;
alter table public.recall_events replica identity full;
alter table public.graph_nodes replica identity full;
alter table public.graph_edges replica identity full;

-- From 004_wearer_membership.sql
-- A wearer is a family member, not an owner of a contributor Keeper.
create table if not exists public.wearer_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  family_id text not null references public.wearer(family_id),
  unique (user_id, family_id)
);
alter table public.wearer_accounts enable row level security;
revoke all on public.wearer_accounts from anon, authenticated;
grant select on public.wearer_accounts to authenticated;
grant all on public.wearer_accounts to service_role;
drop policy if exists own_wearer_membership on public.wearer_accounts;
create policy own_wearer_membership on public.wearer_accounts for select to authenticated using (
  user_id::text = auth.jwt()->>'sub' and family_id = auth.jwt()->'app_metadata'->>'kin_family_id'
);
create or replace function public.kin_has_membership() returns boolean language sql stable security definer
set search_path = public, pg_temp as $$
  select case when auth.jwt()->'app_metadata'->>'kin_role' = 'wearer' then
    exists (select 1 from public.wearer_accounts w where w.user_id::text = auth.jwt()->>'sub'
      and w.family_id = auth.jwt()->'app_metadata'->>'kin_family_id')
  else exists (select 1 from public.relatives r where r.id::text = auth.jwt()->'app_metadata'->>'kin_contributor_id'
    and r.family_id = auth.jwt()->'app_metadata'->>'kin_family_id') end
$$;
do $$ declare t text; begin
  foreach t in array array['relatives','wearer','memories','graph_nodes','graph_edges','recall_events','weaver_questions'] loop
    execute format('drop policy if exists family_read on public.%I', t);
    execute format('drop policy if exists family_read on public.%I', t);
    execute format('create policy family_read on public.%I for select to authenticated using (family_id = (auth.jwt()->''app_metadata''->>''kin_family_id'') and public.kin_has_membership())', t);
  end loop;
end $$;
drop policy if exists family_media_read on storage.objects;
drop policy if exists family_media_read on storage.objects;
create policy family_media_read on storage.objects for select to authenticated using (
  bucket_id = 'media' and (storage.foldername(name))[1] = auth.jwt()->'app_metadata'->>'kin_family_id'
  and public.kin_has_membership()
);

-- From 006_explicit_api_grants.sql
-- Fresh Supabase projects may not provide the old project's default table grants.
-- Keep authorization in the existing RLS policies; never expose face descriptors.
grant usage on schema public to authenticated, service_role;
grant select, insert, update, delete on table
  public.relatives, public.wearer, public.memories, public.graph_nodes,
  public.graph_edges, public.provenance, public.face_embeddings,
  public.recall_events, public.weaver_questions, public.ingestion_receipts,
  public.wearer_accounts
to service_role;

grant select on table
  public.relatives, public.wearer, public.memories, public.graph_nodes,
  public.graph_edges, public.provenance, public.recall_events,
  public.weaver_questions, public.wearer_accounts
to authenticated;

revoke all on public.face_embeddings, public.ingestion_receipts from anon, authenticated;

-- From 007_self_contribution.sql
-- The wearer contributes their own memories.
--
-- A wearer becomes a Keeper owner like any relative, so their stories flow
-- through the existing ingestion, retrieval and provenance paths unchanged.
-- No gate change is needed: evaluateGate already requires two distinct
-- contributors, so a self-memory can corroborate but never speak alone.
--
-- Capture is bounded. While `self_capture_open` is true, self contributions
-- commit directly. Once the family closes the window, the wearer keeps
-- recording exactly as before, but each contribution parks in
-- `pending_contributions` until a contributor approves it. The wearer never
-- sees a door close; only what the system does with the recording changes.

alter table public.relatives add column if not exists is_self boolean not null default false;
create unique index if not exists relatives_one_self_per_family on public.relatives(family_id) where is_self;

-- Only meaningful on the is_self row. True = self contributions commit directly.
alter table public.relatives add column if not exists self_capture_open boolean not null default true;

-- A self contribution recorded after the window closed, held for family review.
-- `payload` is the exact commit_ingestion argument, replayed verbatim on approval.
create table if not exists public.pending_contributions (
  id uuid primary key,
  family_id text not null,
  contributor_id uuid not null references public.relatives(id) on delete cascade,
  kind text not null check (kind in ('photo','story','answer')),
  preview text not null,                -- the wearer's own words, for the reviewer
  media_path text,
  payload jsonb not null,
  state text not null default 'pending' check (state in ('pending','approved','rejected')),
  reviewed_by uuid references public.relatives(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists pending_contributions_family_state
  on public.pending_contributions(family_id, state, created_at desc);

alter table public.pending_contributions enable row level security;
revoke all on public.pending_contributions from anon, authenticated;
grant select on public.pending_contributions to authenticated;
grant all on public.pending_contributions to service_role;

-- Contributors review; the wearer never reads their own review queue.
drop policy if exists family_pending_read on public.pending_contributions;
drop policy if exists family_pending_read on public.pending_contributions;
create policy family_pending_read on public.pending_contributions for select to authenticated using (
  family_id = (auth.jwt()->'app_metadata'->>'kin_family_id')
  and public.kin_has_membership()
  and coalesce(auth.jwt()->'app_metadata'->>'kin_role', '') is distinct from 'wearer'
);

-- Serialize capture, retries and review with commit_ingestion's family lock.
-- Lock order is always family advisory lock, then relative/queue row locks.
create or replace function public.capture_self_contribution(payload jsonb, preview text)
returns jsonb language plpgsql set search_path = public, extensions as $$
declare
  family text := payload->>'family_id';
  owner uuid := (payload->>'contributor_id')::uuid;
  operation uuid := (payload->>'id')::uuid;
  keeper public.relatives%rowtype;
  held public.pending_contributions%rowtype;
  receipt public.ingestion_receipts%rowtype;
begin
  if family is null or owner is null or operation is null
    or payload->>'request_hash' is null or payload->'response' is null
    or payload->'source'->>'type' is distinct from 'human'
    or payload->'memory'->>'id' is distinct from operation::text
    or payload->'memory'->>'family_id' is distinct from family
    or payload->'memory'->>'contributor_id' is distinct from owner::text then
    raise exception 'Invalid self contribution' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(family, 0));
  select * into keeper from public.relatives where id = owner and family_id = family and is_self for update;
  if not found then raise exception 'Self membership required' using errcode = '42501'; end if;
  select * into held from public.pending_contributions where id = operation for update;
  if found then
    if held.family_id is distinct from family or held.contributor_id is distinct from owner
      or held.payload->>'request_hash' is distinct from payload->>'request_hash' then
      raise exception 'Idempotency conflict' using errcode = '23505';
    end if;
    if held.state = 'rejected' then raise exception 'Contribution rejected' using errcode = '23505'; end if;
    return (held.payload->'response') || jsonb_build_object('pending_review', held.state = 'pending');
  end if;
  select * into receipt from public.ingestion_receipts where id = operation;
  if found then
    return public.commit_ingestion(payload); -- validates receipt ownership and hash
  end if;
  if keeper.self_capture_open then return public.commit_ingestion(payload); end if;
  insert into public.pending_contributions(id, family_id, contributor_id, kind, preview, media_path, payload)
    values(operation, family, owner, payload->'memory'->>'kind', left(preview, 2000),
      payload->'memory'->>'media_path', payload);
  return (payload->'response') || jsonb_build_object('pending_review', true);
end;
$$;

create or replace function public.review_self_contribution(family text, reviewer uuid, contribution uuid, decision text)
returns jsonb language plpgsql set search_path = public, extensions as $$
declare
  held public.pending_contributions%rowtype;
  target_state text;
  result jsonb;
begin
  if decision not in ('approve', 'reject') or decision is null then
    raise exception 'Invalid decision' using errcode = '22023';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(family, 0));
  if not exists(select 1 from public.relatives where id = reviewer and family_id = family and not is_self) then
    raise exception 'Family reviewer required' using errcode = '42501';
  end if;
  select * into held from public.pending_contributions where id = contribution and family_id = family for update;
  if not found then raise exception 'Contribution not found' using errcode = 'P0002'; end if;
  target_state := case decision when 'approve' then 'approved' else 'rejected' end;
  if held.state <> 'pending' and held.state <> target_state then
    raise exception 'Contribution already reviewed' using errcode = '23505';
  end if;
  if target_state = 'approved' then result := public.commit_ingestion(held.payload); end if;
  if held.state = 'pending' then
    update public.pending_contributions set state = target_state, reviewed_by = reviewer, reviewed_at = now()
      where id = contribution;
  end if;
  return jsonb_build_object('id', contribution, 'state', target_state, 'result', result);
end;
$$;

revoke all on function public.capture_self_contribution(jsonb, text) from public, anon, authenticated;
revoke all on function public.review_self_contribution(text, uuid, uuid, text) from public, anon, authenticated;
grant execute on function public.capture_self_contribution(jsonb, text) to service_role;
grant execute on function public.review_self_contribution(text, uuid, uuid, text) to service_role;

-- From 008_living_stories.sql
-- Timing metadata belongs to the original memory and inherits its RLS/deletion.
alter table public.memories
  add column if not exists audio_segments jsonb not null default '[]'::jsonb
  check (jsonb_typeof(audio_segments) = 'array');

comment on column public.memories.audio_segments is
  'Continuous original-audio passages: [{start: seconds, end: seconds, text: verbatim transcript}]. Empty for older recordings.';

-- Preserve the existing atomic ingestion and wearer-review RPCs. Timing is
-- committed inside memory.source; mirror it on insert/update for story readers.
create or replace function public.sync_memory_audio_segments() returns trigger
language plpgsql set search_path = public as $$
begin
  if jsonb_typeof(new.source->'audio_segments') = 'array' then
    new.audio_segments := new.source->'audio_segments';
  end if;
  new.audio_segments := coalesce(new.audio_segments, '[]'::jsonb);
  return new;
end;
$$;
drop trigger if exists sync_memory_audio_segments on public.memories;
create trigger sync_memory_audio_segments before insert or update of source on public.memories
for each row execute function public.sync_memory_audio_segments();
update public.memories set audio_segments = source->'audio_segments'
where jsonb_typeof(source->'audio_segments') = 'array';

-- From 009_family_accounts.sql
-- Private family accounts. Run after main migrations 001–008. New accounts create empty
-- family libraries; this migration never inserts demo memories.

create table if not exists public.families (
  id text primary key,
  owner_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create table if not exists public.family_members (
  user_id uuid primary key references auth.users(id) on delete cascade,
  family_id text not null references public.families(id) on delete cascade,
  relative_id uuid not null unique references public.relatives(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table if not exists public.family_invites (
  token uuid primary key default gen_random_uuid(),
  family_id text not null references public.families(id) on delete cascade,
  expires_at timestamptz not null default (now() + interval '7 days'),
  created_at timestamptz not null default now()
);
insert into public.families(id) select family_id from public.wearer on conflict do nothing;

create or replace function public.kin_family_id() returns text
language sql stable security definer set search_path = '' as $$
  select family_id from public.family_members where user_id = auth.uid()
$$;
revoke all on function public.kin_family_id() from public, anon;
grant execute on function public.kin_family_id() to authenticated, service_role;

alter table public.families enable row level security;
alter table public.family_members enable row level security;
alter table public.family_invites enable row level security;
drop policy if exists "family read" on public.families;
create policy "family read" on public.families for select to authenticated using (id = public.kin_family_id());
drop policy if exists "membership read" on public.family_members;
create policy "membership read" on public.family_members for select to authenticated using (family_id = public.kin_family_id());
drop policy if exists "owner invite read" on public.family_invites;
create policy "owner invite read" on public.family_invites for select to authenticated using (
  exists(select 1 from public.families f where f.id = family_id and f.owner_id = auth.uid())
);
grant select on public.families, public.family_members, public.family_invites to authenticated;
grant all on public.families, public.family_members, public.family_invites to service_role;

-- Replace the prototype's public read policies, including direct REST access.
do $$ declare t text; begin
  foreach t in array array['relatives','wearer','memories','graph_nodes','graph_edges','recall_events','weaver_questions'] loop
    execute format('drop policy if exists %I on public.%I', 'anon read ' || t, t);
    execute format('drop policy if exists %I on public.%I', 'member read', t);
    execute format('create policy %I on public.%I for select to authenticated using (family_id = public.kin_family_id())', 'member read', t);
  end loop;
end $$;
drop policy if exists "anon read provenance" on public.provenance;
drop policy if exists "member read" on public.provenance;
create policy "member read" on public.provenance for select to authenticated using (
  exists(select 1 from public.memories m where m.id = memory_id and m.family_id = public.kin_family_id())
);
grant select on public.relatives, public.wearer, public.memories, public.graph_nodes,
  public.graph_edges, public.provenance, public.recall_events,
  public.weaver_questions to authenticated;
drop policy if exists account_media_read on storage.objects;
drop policy if exists account_media_read on storage.objects;
create policy account_media_read on storage.objects for select to authenticated using (
  bucket_id = 'media' and (storage.foldername(name))[1] = public.kin_family_id()
);
-- Media is delivered by signed URLs after the server verifies family membership.
update storage.buckets set public = false where id = 'media';

create or replace function public.create_kin_family(loved_one text, member_name text, relationship text)
returns text language plpgsql security definer set search_path = '' as $$
declare uid uuid := auth.uid(); fid text := gen_random_uuid()::text; rid uuid;
begin
  if uid is null then raise exception 'Sign in first'; end if;
  perform pg_advisory_xact_lock(hashtextextended(uid::text, 0));
  if exists(select 1 from public.family_members where user_id = uid) then raise exception 'Already a family member'; end if;
  if length(trim(loved_one)) not between 1 and 80 or length(trim(member_name)) not between 1 and 80 or length(trim(relationship)) not between 1 and 60 then raise exception 'Please complete all names and relationships'; end if;
  insert into public.families(id,owner_id) values(fid,uid);
  insert into public.wearer(family_id,name) values(fid,trim(loved_one));
  insert into public.relatives(family_id,name,relation_to_wearer,color) values(fid,trim(member_name),trim(relationship),'#6958C9') returning id into rid;
  insert into public.graph_nodes(family_id,type,label,relation_to_wearer) values(fid,'person',trim(loved_one),'self');
  insert into public.family_members(user_id,family_id,relative_id) values(uid,fid,rid);
  return fid;
end $$;
create or replace function public.join_kin_family(invite_code uuid, member_name text, relationship text)
returns text language plpgsql security definer set search_path = '' as $$
declare uid uuid := auth.uid(); fid text; rid uuid;
begin
  if uid is null then raise exception 'Sign in first'; end if;
  perform pg_advisory_xact_lock(hashtextextended(uid::text, 0));
  if exists(select 1 from public.family_members where user_id = uid) then raise exception 'Already a family member'; end if;
  if length(trim(member_name)) not between 1 and 80 or length(trim(relationship)) not between 1 and 60 then raise exception 'Please complete your name and relationship'; end if;
  select family_id into fid from public.family_invites where token = invite_code and expires_at > now();
  if fid is null then raise exception 'This invitation has expired or is no longer available'; end if;
  insert into public.relatives(family_id,name,relation_to_wearer,color) values(fid,trim(member_name),trim(relationship),'#287D75') returning id into rid;
  insert into public.family_members(user_id,family_id,relative_id) values(uid,fid,rid);
  return fid;
end $$;
revoke all on function public.create_kin_family(text,text,text), public.join_kin_family(uuid,text,text) from public,anon;
grant execute on function public.create_kin_family(text,text,text), public.join_kin_family(uuid,text,text) to authenticated;
-- The redesigned UI never receives stored face descriptors or face-retrieval RPCs.
revoke all on public.face_embeddings from anon, authenticated;
revoke all on function public.match_faces(vector,text,int), public.match_memories(vector,uuid,int) from public,anon,authenticated;
grant execute on function public.match_faces(vector,text,int), public.match_memories(vector,uuid,int) to service_role;
do $$ declare t text; begin
  foreach t in array array['memories','relatives','family_members'] loop
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename=t) then
      execute format('alter publication supabase_realtime add table public.%I', t);
    end if;
  end loop;
end $$;

-- From 010_loved_one_invites.sql
-- Separate the person using recognition from the people contributing memories.
-- Existing accounts and invitations remain contributors. No memories are changed.

-- The original feature branch used different migrations numbered 002–004.
-- Detect that schema before changing any account objects.
do $$ begin
  if to_regclass('public.wearer_accounts') is null
    or to_regclass('public.ingestion_receipts') is null
    or to_regclass('public.pending_contributions') is null then
    raise exception 'The database is missing main-branch prerequisites for migration 010.'
      using hint = 'For the original pull-apart branch database, run the entire supabase/upgrades/pull_apart_to_main.sql file instead. It preserves existing data.';
  end if;
end $$;
alter table public.family_members add column if not exists role text not null default 'contributor';
alter table public.family_members alter column relative_id drop not null;
alter table public.family_members drop constraint if exists family_member_role;
alter table public.family_members add constraint family_member_role check (
  (role = 'contributor' and relative_id is not null) or
  (role = 'loved_one' and relative_id is null)
);
create unique index if not exists one_loved_one_per_family on public.family_members(family_id) where role = 'loved_one';
alter table public.family_invites add column if not exists role text not null default 'contributor';
alter table public.family_invites add column if not exists used_at timestamptz;
alter table public.family_invites drop constraint if exists family_invite_role;
alter table public.family_invites add constraint family_invite_role check (role in ('contributor','loved_one'));

create or replace function public.join_kin_family(invite_code uuid, member_name text, relationship text)
returns text language plpgsql security definer set search_path = '' as $$
declare uid uuid := auth.uid(); invitation public.family_invites%rowtype; rid uuid;
begin
  if uid is null then raise exception 'Sign in first'; end if;
  perform pg_advisory_xact_lock(hashtextextended(uid::text, 0));
  if exists(select 1 from public.family_members where user_id = uid) then raise exception 'Already a family member'; end if;
  select * into invitation from public.family_invites
    where token = invite_code and expires_at > now() and used_at is null for update;
  if invitation.token is null then raise exception 'This invitation has expired or has already been used'; end if;
  if invitation.role = 'loved_one' then
    -- Serialize claims even when an organizer created more than one invitation.
    perform pg_advisory_xact_lock(hashtextextended(invitation.family_id, 1));
    if exists(select 1 from public.family_members where family_id = invitation.family_id and role = 'loved_one') then
      raise exception 'Your loved one already has an account in this family';
    end if;
    insert into public.family_members(user_id,family_id,relative_id,role)
      values(uid,invitation.family_id,null,'loved_one');
    update public.family_invites set used_at = now() where token = invite_code;
  else
    if member_name is null or relationship is null or length(trim(member_name)) not between 1 and 80 or length(trim(relationship)) not between 1 and 60 then
      raise exception 'Please complete your name and relationship';
    end if;
    insert into public.relatives(family_id,name,relation_to_wearer,color)
      values(invitation.family_id,trim(member_name),trim(relationship),'#287D75') returning id into rid;
    insert into public.family_members(user_id,family_id,relative_id,role)
      values(uid,invitation.family_id,rid,'contributor');
  end if;
  return invitation.family_id;
end $$;
revoke all on function public.join_kin_family(uuid,text,text) from public,anon;
grant execute on function public.join_kin_family(uuid,text,text) to authenticated;
-- Preserve main's already-provisioned accounts. No memories, embeddings, or
-- existing memberships are rewritten. Claims remain admin-managed.
insert into public.families(id,owner_id)
select u.raw_app_meta_data->>'kin_family_id', u.id from auth.users u
where u.raw_app_meta_data->>'kin_admin' = 'true'
  and exists(select 1 from public.relatives r where r.id::text=u.raw_app_meta_data->>'kin_contributor_id'
    and r.family_id=u.raw_app_meta_data->>'kin_family_id')
on conflict(id) do update set owner_id=coalesce(public.families.owner_id,excluded.owner_id);
insert into public.family_members(user_id,family_id,relative_id,role)
select u.id,r.family_id,r.id,'contributor' from auth.users u
join public.relatives r on r.id::text=u.raw_app_meta_data->>'kin_contributor_id'
  and r.family_id=u.raw_app_meta_data->>'kin_family_id'
where coalesce(u.raw_app_meta_data->>'kin_role','') <> 'wearer'
on conflict do nothing;
insert into public.family_members(user_id,family_id,relative_id,role)
select w.user_id,w.family_id,null,'loved_one' from public.wearer_accounts w
join public.families f on f.id=w.family_id
on conflict do nothing;

-- Provision main's wearer membership alongside a new loved-one invitation.
-- A new wearer also receives an is_self Keeper, with review enabled by default.
create or replace function public.sync_kin_account() returns trigger
language plpgsql security definer set search_path='' as $$
begin
  if new.role='loved_one' then
    insert into public.wearer_accounts(user_id,family_id) values(new.user_id,new.family_id) on conflict(user_id) do nothing;
    insert into public.relatives(family_id,name,relation_to_wearer,color,is_self,self_capture_open)
    select new.family_id,w.name,'self','#6958C9',true,false from public.wearer w
    where w.family_id=new.family_id and not exists(select 1 from public.relatives r where r.family_id=new.family_id and r.is_self);
  end if;
  update auth.users set raw_app_meta_data=coalesce(raw_app_meta_data,'{}'::jsonb) || jsonb_build_object(
    'kin_family_id',new.family_id,'kin_contributor_id',new.relative_id,
    'kin_role',case when new.role='loved_one' then 'wearer' else 'contributor' end,
    'kin_admin',exists(select 1 from public.families f where f.id=new.family_id and f.owner_id=new.user_id)
  ) where id=new.user_id;
  return new;
end $$;
revoke all on function public.sync_kin_account() from public,anon,authenticated;
drop trigger if exists sync_kin_account on public.family_members;
create trigger sync_kin_account after insert on public.family_members for each row execute function public.sync_kin_account();

-- From 011_rust_face_models.sql
create or replace function public.commit_ingestion(payload jsonb)
returns jsonb
language plpgsql
set search_path = public, extensions
as $$
declare
  operation_id uuid := (payload->>'id')::uuid;
  family text := payload->>'family_id';
  contributor uuid := (payload->>'contributor_id')::uuid;
  receipt public.ingestion_receipts%rowtype;
  memory_record public.memories%rowtype;
  face_record public.face_embeddings%rowtype;
  question public.weaver_questions%rowtype;
  node_record public.graph_nodes%rowtype;
  edge_record public.graph_edges%rowtype;
  provenance_record public.provenance%rowtype;
  item jsonb;
begin
  if family is null or contributor is null or operation_id is null
     or payload->>'request_hash' is null or payload->'response' is null
     or payload->'source'->>'type' is distinct from 'human' then
    raise exception 'Invalid ingestion payload';
  end if;
  perform pg_advisory_xact_lock(hashtextextended(family, 0));
  if not exists (select 1 from public.relatives where id = contributor and family_id = family) then
    raise exception 'Contributor scope mismatch';
  end if;
  select * into receipt from public.ingestion_receipts where id = operation_id;
  if found then
    if receipt.family_id is distinct from family
       or receipt.contributor_id is distinct from contributor
       or receipt.request_hash is distinct from payload->>'request_hash' then
      raise exception 'Idempotency conflict' using errcode = '23505';
    end if;
    return receipt.response;
  end if;

  if payload ? 'face' then
    face_record := jsonb_populate_record(null::public.face_embeddings,
      (payload->'face') || jsonb_build_object('descriptor', (payload->'face'->'descriptor')::text,
        'model', payload->'source'->>'model'));
    if face_record.id is distinct from operation_id
       or face_record.family_id is distinct from family
       or face_record.contributor_id is distinct from contributor
       or payload->'source'->>'consent' is distinct from 'true'
       or coalesce(payload->'source'->>'model', '') not in ('face-api-1.7.15:ssd-mobilenetv1:landmark68:recognition128:rgb-exif-v1', 'kin-yunet-2023mar:sface-2021dec:recognition128:rgb-exif-v1')
       or vector_dims(face_record.descriptor) is distinct from 128 then
      raise exception 'Invalid enrollment';
    end if;
    if not exists (select 1 from public.memories where id = face_record.memory_id
      and family_id = family and contributor_id = contributor and kind = 'photo')
      or not exists (select 1 from public.graph_nodes where id = face_record.person_node_id
      and family_id = family and type = 'person') then
      raise exception 'Enrollment scope mismatch';
    end if;
    insert into public.face_embeddings select face_record.*;
    insert into public.provenance(memory_id, node_id, contributor_id)
      select face_record.memory_id, face_record.person_node_id, contributor
      where not exists (select 1 from public.provenance where memory_id = face_record.memory_id
        and node_id = face_record.person_node_id and contributor_id = contributor);
  else
    memory_record := jsonb_populate_record(null::public.memories,
      (payload->'memory') || jsonb_build_object('embedding', (payload->'memory'->'embedding')::text));
    memory_record.source := payload->'source';
    memory_record.verified_facts := coalesce(payload->'memory'->'verified_facts', '[]'::jsonb);
    if memory_record.id is distinct from operation_id
       or memory_record.family_id is distinct from family
       or memory_record.contributor_id is distinct from contributor then
      raise exception 'Memory scope mismatch';
    end if;
    if memory_record.kind = 'answer' then
      select * into question from public.weaver_questions
        where id = memory_record.source_question_id for update;
      if not found or question.family_id is distinct from family
         or question.target_relative_id is distinct from contributor then
        raise exception 'Question scope mismatch';
      end if;
      if question.status <> 'open' then
        raise exception 'Question already answered' using errcode = '23505';
      end if;
    elsif memory_record.source_question_id is not null then
      raise exception 'Unexpected question';
    end if;
    memory_record.created_at := now();
    insert into public.memories select memory_record.*;

    for item in select value from jsonb_array_elements(payload->'nodes') loop
      node_record := jsonb_populate_record(null::public.graph_nodes, item);
      if node_record.family_id is distinct from family then raise exception 'Node scope mismatch'; end if;
      node_record.created_at := now();
      insert into public.graph_nodes select node_record.* on conflict (id) do nothing;
      if not exists (select 1 from public.graph_nodes where id = node_record.id
        and family_id = family and type = node_record.type and label = node_record.label) then
        raise exception 'Node collision';
      end if;
    end loop;
    for item in select value from jsonb_array_elements(payload->'edges') loop
      edge_record := jsonb_populate_record(null::public.graph_edges, item);
      if edge_record.family_id is distinct from family
         or not exists (select 1 from public.graph_nodes where id = edge_record.from_node and family_id = family)
         or not exists (select 1 from public.graph_nodes where id = edge_record.to_node and family_id = family)
         or edge_record.rel not in ('sibling_of','child_of','parent_of','grandchild_of','spouse_of','friend_of',
           'participates_in','started_by','taught_by','origin','located_at','wears','owns','made','happens_on') then
        raise exception 'Invalid edge';
      end if;
      edge_record.created_at := now();
      insert into public.graph_edges select edge_record.* on conflict (id) do nothing;
      if not exists (select 1 from public.graph_edges where id = edge_record.id and family_id = family
        and from_node = edge_record.from_node and to_node = edge_record.to_node and rel = edge_record.rel) then
        raise exception 'Edge collision';
      end if;
    end loop;
    for item in select value from jsonb_array_elements(payload->'provenance') loop
      provenance_record := jsonb_populate_record(null::public.provenance, item);
      if provenance_record.memory_id is distinct from operation_id
         or provenance_record.contributor_id is distinct from contributor
         or (provenance_record.node_id is null) = (provenance_record.edge_id is null)
         or (provenance_record.node_id is not null and not exists
           (select 1 from public.graph_nodes where id = provenance_record.node_id and family_id = family))
         or (provenance_record.edge_id is not null and not exists
           (select 1 from public.graph_edges where id = provenance_record.edge_id and family_id = family)) then
        raise exception 'Provenance scope mismatch';
      end if;
      insert into public.provenance select provenance_record.* on conflict (id) do nothing;
    end loop;
    for item in select value from jsonb_array_elements(memory_record.verified_facts) loop
      if item->>'memoryId' is distinct from operation_id::text
         or item->>'contributorId' is distinct from contributor::text
         or nullif(item->>'text', '') is null
         or jsonb_typeof(item->'sourceSpan') is distinct from 'object'
         or jsonb_typeof(item->'sourceSpan'->'start') is distinct from 'number'
         or jsonb_typeof(item->'sourceSpan'->'end') is distinct from 'number'
         or (item->'sourceSpan'->>'start')::int < 0
         or (item->'sourceSpan'->>'end')::int <= (item->'sourceSpan'->>'start')::int
         or position(item->>'text' in coalesce(memory_record.transcript, memory_record.source->>'caption', '')) = 0
         or not exists (select 1 from public.provenance where memory_id = operation_id
           and node_id = (item->>'subjectNodeId')::uuid and contributor_id = contributor) then
        raise exception 'Invalid verified human fact';
      end if;
    end loop;
    if memory_record.kind = 'answer' then
      update public.weaver_questions set status = 'answered', answer_memory_id = operation_id
        where id = memory_record.source_question_id;
    end if;
  end if;

  insert into public.ingestion_receipts(id, family_id, contributor_id, request_hash, response, source)
    values (operation_id, family, contributor, payload->>'request_hash', payload->'response', payload->'source');
  return payload->'response';
end;
$$;

revoke all on function public.commit_ingestion(jsonb) from public, anon, authenticated;
grant execute on function public.commit_ingestion(jsonb) to service_role;

notify pgrst, 'reload schema';

-- Existing branch memberships predate the INSERT trigger in 010. Bridge them
-- too, without recreating accounts, changing IDs, or touching their passwords.
do $$ begin
  if exists(select 1 from public.family_members m join public.wearer_accounts w on w.user_id=m.user_id
    where m.role='loved_one' and m.family_id<>w.family_id) then
    raise exception 'Conflicting wearer membership needs review. Nothing was changed.';
  end if;
end $$;
insert into public.wearer_accounts(user_id,family_id)
select user_id,family_id from public.family_members where role='loved_one'
on conflict(user_id) do nothing;
insert into public.relatives(family_id,name,relation_to_wearer,color,is_self,self_capture_open)
select w.family_id,w.name,'self','#6958C9',true,false from public.wearer w
where exists(select 1 from public.wearer_accounts a where a.family_id=w.family_id)
  and not exists(select 1 from public.relatives r where r.family_id=w.family_id and r.is_self);
update auth.users u set raw_app_meta_data=coalesce(u.raw_app_meta_data,'{}'::jsonb) || jsonb_build_object(
  'kin_family_id',m.family_id,'kin_contributor_id',m.relative_id,
  'kin_role',case when m.role='loved_one' then 'wearer' else 'contributor' end,
  'kin_admin',m.role='contributor' and exists(select 1 from public.families f where f.id=m.family_id and f.owner_id=u.id)
) from public.family_members m where m.user_id=u.id;
-- The old branch granted a face-descriptor RPC to browsers. Its implementation
-- remains for historical compatibility, but only server access is permitted.
do $$ begin
  if to_regprocedure('public.match_keeper_faces(vector,text,uuid,integer)') is not null then
    revoke all on function public.match_keeper_faces(vector,text,uuid,integer) from public,anon,authenticated;
    grant execute on function public.match_keeper_faces(vector,text,uuid,integer) to service_role;
  end if;
end $$;
notify pgrst, 'reload schema';
commit;
